### PR TITLE
DES-13242: Installer changes for AllUsers/SingleUser + PodUrl update

### PR DESCRIPTION
**Pull request by rbarros-daitan**

### CODE REVIEW

**Comment by lneir** [comment]
i took a look at installer...
- take a look at electron installer and follow what is done there... https://github.com/symphonyoss/SymphonyElectron/tree/master/installer
- the first screen should ask 'install for all' or 'install per user' since the default path (on 2nd screen) will change depending on that selection.
- also put url selection on 2nd screen.
- make sure wording is the same as electron wrapper as well.

**Comment by rbarros-daitan** [comment]
Changes applied following Symphony Electron´s design.

**Comment by rbarros-daitan** [comment]
@lneir , hi. Changes on all/single users are completed. Could you please review? Thanks.

**Comment by lneir** [comment]
lgtm

**Pull request merged**
